## 003 Matrices of Simple Linear Algebra



After Linear Algebra Matrices - I did want to learn coding it in Python using Numpy.

In [1]:
import numpy as np

The following are set examples presented as A, B, C, D, and the scalar k.

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
B

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
C = np.array([[1, 2], [3, 4], [5, 6]])
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
D = np.array([[2,4,5],[1,3,6],[7,9,8]])
D

array([[2, 4, 5],
       [1, 3, 6],
       [7, 9, 8]])

In [23]:
k = 2
k

2

Below are samples of equations used.

In [15]:
transpose_C = np.transpose(C)
transpose_C

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
AplusB = A + B
print(f"A + B is equal to: {AplusB}")

A + B is equal to: [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [19]:
AminusB = A - B
print(f"A - B is = {AminusB}")

A - B is = [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [20]:
Asquared = A**2
print(f"A squared is: {Asquared}")

A squared is: [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
twoA = 2**A
print(f"2 times A is : {twoA}")

2 times A is : [[  2   4   8]
 [ 16  32  64]
 [128 256 512]]


In [24]:
kA = k * A
kA

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [35]:
AB = A * B
AB

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [32]:
AD_dot = np.dot(A, D)
AD_dot

array([[ 25,  37,  41],
       [ 55,  85,  98],
       [ 85, 133, 155]])

In [33]:
DA_dot = np.dot(D, A)
DA_dot

array([[ 53,  64,  75],
       [ 55,  65,  75],
       [ 99, 123, 147]])

In [36]:
ABD = D * (A + B)
ABD

array([[20, 40, 50],
       [10, 30, 60],
       [70, 90, 80]])

In [37]:
ABD2 = (D * A) + (D * B)
ABD2

array([[20, 40, 50],
       [10, 30, 60],
       [70, 90, 80]])

In [38]:
Negatives = -(A)
Negatives

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [40]:
Negatives2 = -(A - B)
Negatives2

array([[ 8,  6,  4],
       [ 2,  0, -2],
       [-4, -6, -8]])

For special cases:

In [48]:
numpysqrt = np.sqrt(A)
numpysqrt

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [49]:
numpylog = np.log10(B)
numpylog

array([[0.95424251, 0.90308999, 0.84509804],
       [0.77815125, 0.69897   , 0.60205999],
       [0.47712125, 0.30103   , 0.        ]])

In [50]:
numpytan = np.tan(A)
numpytan

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

Sample Equations:

In [42]:
Sample_Eq1 = 2 * (-D * (k*A))**2
Sample_Eq1

array([[   32,   512,  1800],
       [  128,  1800, 10368],
       [19208, 41472, 41472]])

In [43]:
Sample_Eq2 = k * (A + D - B)
Sample_Eq2

array([[-12,  -4,   2],
       [ -2,   6,  16],
       [ 22,  30,  32]])

In [46]:
Sample_Eq3 = -B + A * (k + A + D**0)
Sample_Eq3

array([[ -5,   2,  11],
       [ 22,  35,  50],
       [ 67,  86, 107]])

### If you want to experiment with it

Below, you can define your own matrix equation as a string. The code will then evaluate this string to compute the result. This allows you to experiment with various combinations of matrices (`A`, `B`, `C_3x3`, `D`) and the scalar `k`, as well as `numpy` functions like `np.dot()` for matrix multiplication.

In [47]:
# Define your equation as a string here
# Example: 'np.dot(A, D) + k * B'
# Example: '2 * (A + B)'
# Example: 'np.transpose(D) @ A'

user_equation_string = 'np.dot(A, B) - D'

try:

    dynamic_result = eval(user_equation_string)
    print(f"Result of '{user_equation_string}':")
    display(dynamic_result)
except Exception as e:
    print(f"Error evaluating equation: {e}")
    print("Please ensure your equation is syntactically correct and uses defined variables.")

Result of 'np.dot(A, B) - D':


array([[ 28,  20,  13],
       [ 83,  66,  48],
       [131, 105,  82]])

My apologies for the lazy writing haha. I did this as an exercise for matrices. Thank you for checking!
